--CREATE TABLE ingrediente (
--   id_ingrediente BIGINT AUTO_INCREMENT PRIMARY KEY,
--   nome_ingrediente VARCHAR(50) NOT NULL,
--   valor_ingrediente DECIMAL(4,2) NOT NULL
--);
--
--CREATE TABLE pedido
--(
--    id_pedido BIGINT AUTO_INCREMENT PRIMARY KEY,
--    preco_total_pedido DECIMAL(4, 2) NOT NULL
--);
--
--CREATE TABLE pedido_ingrediente
--(
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    id_pedido BIGINT,
--    id_ingrediente BIGINT,
--    FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
--    FOREIGN KEY (id_ingrediente) REFERENCES ingrediente(id_ingrediente)
--);
--
--CREATE TABLE lanche (
--   id_lanche BIGINT AUTO_INCREMENT PRIMARY KEY,
--   nome_lanche_lanche VARCHAR(255) NOT NULL,
--   customizado_lanche BOOLEAN NOT NULL
--);
--
--CREATE TABLE usuario_admin
--(
--    id_usuario_admin BIGINT AUTO_INCREMENT PRIMARY KEY,
--    nome_admin_usuario_admin VARCHAR(255) NOT NULL,
--    role_usuario_admin VARCHAR(255) NOT NULL
--);
--
--CREATE TABLE promocao
--(
--    id_promocao BIGINT AUTO_INCREMENT PRIMARY KEY,
--    nome_promocao_promocao VARCHAR(255) NOT NULL,
--    regra_de_negocio_promocao VARCHAR(255) NOT NULL,
--    lanche_id BIGINT,
--    FOREIGN KEY (lanche_id) REFERENCES lanche(id_lanche)
--);

INSERT INTO LANCHE (ID_LANCHE, NOME_LANCHE_LANCHE, CUSTOMIZADO_LANCHE) VALUES (1, 'Completo com Linguiça', FALSE);
INSERT INTO INGREDIENTE (ID_INGREDIENTE,NOME_INGREDIENTE, VALOR_INGREDIENTE) VALUES (1, 'Milho', 0.20);
INSERT INTO INGREDIENTE (NOME_INGREDIENTE, VALOR_INGREDIENTE) VALUES ('batata palha', 0.40);
INSERT INTO INGREDIENTE (NOME_INGREDIENTE, VALOR_INGREDIENTE) VALUES ('pão', 2.00);
INSERT INTO INGREDIENTE (NOME_INGREDIENTE, VALOR_INGREDIENTE) VALUES ('linguiça', 3.00);
INSERT INTO INGREDIENTE (NOME_INGREDIENTE, VALOR_INGREDIENTE) VALUES ('salsicha', 2.00);
INSERT INTO INGREDIENTE (NOME_INGREDIENTE, VALOR_INGREDIENTE) VALUES ('ovo de codorna', 0.30);
INSERT INTO INGREDIENTE (NOME_INGREDIENTE, VALOR_INGREDIENTE) VALUES ('purê de batatas', 1.00);
INSERT INTO LANCHE_INGREDIENTE (LANCHE_ID_LANCHE, INGREDIENTES_ID_INGREDIENTE) VALUES (1, 1);
INSERT INTO LANCHE_INGREDIENTE (LANCHE_ID_LANCHE, INGREDIENTES_ID_INGREDIENTE) VALUES (1, 2);
INSERT INTO USUARIO_ADMIN (ID_USUARIO_ADMIN, NOME_ADMIN_USUARIO_ADMIN, ROLE_USUARIO_ADMIN) VALUES (1, 'Paulo', 'admin');

